// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQhrPGDjtIWwceeoeZvwinUbdhznVUKrM',
    appId: '1:485132827111:web:becb086ec9fccf1cc2e542',
    messagingSenderId: '485132827111',
    projectId: 'ibacourse-d90db',
    authDomain: 'ibacourse-d90db.firebaseapp.com',
    storageBucket: 'ibacourse-d90db.appspot.com',
    measurementId: 'G-E285N8NNKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUk13Tt8SrynVPnLF_raR82q7o1Q8aeOQ',
    appId: '1:485132827111:android:4cc349f6ec6bceedc2e542',
    messagingSenderId: '485132827111',
    projectId: 'ibacourse-d90db',
    storageBucket: 'ibacourse-d90db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDoYkMNHhzPO8-D04S7Wb34cHc3y08qAM',
    appId: '1:485132827111:ios:a59dfdd4491a31f3c2e542',
    messagingSenderId: '485132827111',
    projectId: 'ibacourse-d90db',
    storageBucket: 'ibacourse-d90db.appspot.com',
    iosClientId: '485132827111-9pkjiffovhksne8d8h2m5n6idfpegc5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibaCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDoYkMNHhzPO8-D04S7Wb34cHc3y08qAM',
    appId: '1:485132827111:ios:a59dfdd4491a31f3c2e542',
    messagingSenderId: '485132827111',
    projectId: 'ibacourse-d90db',
    storageBucket: 'ibacourse-d90db.appspot.com',
    iosClientId: '485132827111-9pkjiffovhksne8d8h2m5n6idfpegc5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibaCourse',
  );
}
